version: '3.8'

services:
  redmine-report:
    build: .
    container_name: redmine-report-service
    restart: unless-stopped
    network_mode: "host"  # Use host network to access external Redmine server
    environment:
      # Redmine Configuration
      - REDMINE_URL=${REDMINE_URL:-http://192.168.0.222:3000}
      - REDMINE_API_KEY=${REDMINE_API_KEY}

      # Email Configuration (Redmine-compatible settings)
      - SMTP_HOST=${SMTP_HOST:-192.168.0.222}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-GOPEAK@mail.gogopeaks.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-5w~IDW}
      - EMAIL_FROM=${EMAIL_FROM:-GOPEAK@mail.gogopeaks.com}

      # Report Configuration
      - REPORT_DAYS=${REPORT_DAYS:-14}
      - TIMEZONE=${TIMEZONE:-Asia/Taipei}

      # Schedule Configuration (cron format)
      - SCHEDULE_CRON=${SCHEDULE_CRON:-0 8 * * 1}  # Every Monday at 8:00 AM
      
      # Auto-send Configuration  
      - REPORT1_AUTO_SEND=${REPORT1_AUTO_SEND:-true}   # Enable Report 1 auto-send
      - REPORT2_AUTO_SEND=${REPORT2_AUTO_SEND:-true}   # Enable Report 2 auto-send
      - REPORT3_AUTO_SEND=${REPORT3_AUTO_SEND:-false}  # Enable Report 3 auto-send (weekly)
      
      # Custom Recipients (optional, comma-separated emails)
      - REPORT1_RECIPIENTS=${REPORT1_RECIPIENTS:-}     # Custom recipients for Report 1
      - REPORT2_RECIPIENTS=${REPORT2_RECIPIENTS:-}     # Custom recipients for Report 2  
      - REPORT3_RECIPIENTS=${REPORT3_RECIPIENTS:-}     # Custom recipients for Report 3
      
      # Synology DSM Configuration
      - SYNOLOGY_DSM_HOST=${SYNOLOGY_DSM_HOST:-192.168.0.222}
      - SYNOLOGY_DSM_PORT=${SYNOLOGY_DSM_PORT:-5001}
      - SYNOLOGY_DSM_ADMIN_USER=${SYNOLOGY_DSM_ADMIN_USER:-admin}
      - SYNOLOGY_DSM_ADMIN_PASS=${SYNOLOGY_DSM_ADMIN_PASS:-}
      
      # Synology LDAP Configuration  
      - LDAP_HOST=${LDAP_HOST:-192.168.0.222}
      - LDAP_PORT=${LDAP_PORT:-389}
      - LDAP_ADMIN_DN=${LDAP_ADMIN_DN:-uid=df.liao,cn=users,dc=nas,dc=gogopeaks,dc=com}
      - LDAP_ADMIN_PASS=${LDAP_ADMIN_PASS:-}
      - LDAP_BASE_DN=${LDAP_BASE_DN:-dc=nas,dc=gogopeaks,dc=com}
      - LDAP_LOGIN_ATTR=${LDAP_LOGIN_ATTR:-uid}

      # Debug Configuration
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

    # Note: ports not needed in host network mode - service runs on host port 3003

    volumes:
      - /volume1/ai-stack2/redmine-report/output:/app/output:rw
      - /volume1/ai-stack2/redmine-report/src/main/resources/config:/app/src/main/resources/config:ro

    # Note: external_links not needed in host network mode

    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3003/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Synology-specific optimizations
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Note: Redis service removed as host network mode allows direct connection to external Redis if needed